services:
  db:
    image: postgres:15
    container_name: gradehub_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gradehub
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/data:/docker-entrypoint-initdb.d/data
    networks:
      - gradehub_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./backend              # Use the backend directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: gradehub
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gradehub_network

  migrate:
    image: migrate/migrate
    volumes:
      - ./backend/db/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/gradehub?sslmode=disable",
      "up"
    ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gradehub_network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   networks:
  #     - gradehub_network

networks:
  gradehub_network:

volumes:
  pgdata: