# Directory to watch for file changes
root = "."                            # Keep root as current directory
tmp_dir = "./tmp"

# Build Go binary from the backend directory
[build]
cmd = "cd backend && go build -o ../tmp/gradehub.exe ./cmd/main.go"   # Change dir before building
bin = "./tmp/gradehub.exe"
full_bin = "./tmp/gradehub.exe"
include_ext = ["go"]

# Watcher settings
[watcher]
watch = ["./backend"]                 # Watch the backend directory
exclude = ["tmp", "vendor", ".git"]
