# Use the official Golang image for development
FROM golang:1.24 AS builder

# Install Air for hot reloading
RUN go install github.com/air-verse/air@latest

# Set environment variables
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Set working directory
WORKDIR /app

# Copy Go modules and install dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Expose the backend port
EXPOSE 8080

# Use Air for hot reloading
CMD ["air", "-c", "/app/air.toml", "--poll"]
