DROP IF EXISTS "courses";
DROP IF EXISTS "schools";
DROP IF EXISTS "users";
DROP IF EXISTS "status";
DROP IF EXISTS "enrolled";
DROP IF EXISTS "attends";
DROP IF EXISTS "assignments";
DROP IF EXISTS "student_assignment";
DROP IF EXISTS "verification_codes";
